service: appointments-graphql
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 10
  httpApi:
    cors: true

functions:
  appointmentsGraphql:
    handler: src/index.handler
    environment:
      NODE_ENV: production
      DB_URL: ${env:DB_URL}
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET

plugins:
  - serverless-plugin-typescript